/**
 * Canonical domain lookup for well-known companies.
 * Used by the logo proxy (/api/logo?domain=...) to resolve high-quality logos
 * via Clearbit for any company the user enters.
 *
 * Key   = lowercase simplified company name (no Inc./Corp./Ltd.)
 * Value = primary root domain (e.g. "stripe.com", NOT "app.stripe.com")
 *
 * Sources: Fortune 500, Forbes Global 2000, FAANG/major tech, banking,
 * retail, healthcare, energy, consulting, automotive, aerospace, F&B, telecom, media.
 */
export const COMPANY_DOMAINS: Record<string, string> = {
  // ── Technology: FAANG / Mega-cap ─────────────────────────────────────────
  "apple": "apple.com",
  "microsoft": "microsoft.com",
  "google": "google.com",
  "alphabet": "abc.xyz",
  "meta": "meta.com",
  "facebook": "facebook.com",
  "amazon": "amazon.com",
  "netflix": "netflix.com",
  "nvidia": "nvidia.com",

  // ── Technology: Cloud & Enterprise ───────────────────────────────────────
  "salesforce": "salesforce.com",
  "oracle": "oracle.com",
  "ibm": "ibm.com",
  "sap": "sap.com",
  "adobe": "adobe.com",
  "cisco": "cisco.com",
  "intel": "intel.com",
  "amd": "amd.com",
  "qualcomm": "qualcomm.com",
  "broadcom": "broadcom.com",
  "texas instruments": "ti.com",
  "ti": "ti.com",
  "servicenow": "servicenow.com",
  "workday": "workday.com",
  "veeva systems": "veeva.com",
  "veeva": "veeva.com",
  "palo alto networks": "paloaltonetworks.com",
  "crowdstrike": "crowdstrike.com",
  "fortinet": "fortinet.com",
  "zscaler": "zscaler.com",
  "okta": "okta.com",
  "splunk": "splunk.com",
  "datadog": "datadoghq.com",
  "new relic": "newrelic.com",
  "dynatrace": "dynatrace.com",
  "elastic": "elastic.co",
  "mongodb": "mongodb.com",
  "snowflake": "snowflake.com",
  "databricks": "databricks.com",
  "palantir": "palantir.com",
  "c3.ai": "c3.ai",
  "twilio": "twilio.com",
  "zendesk": "zendesk.com",
  "freshworks": "freshworks.com",
  "hubspot": "hubspot.com",
  "docusign": "docusign.com",
  "box": "box.com",
  "dropbox": "dropbox.com",
  "atlassian": "atlassian.com",
  "jira": "atlassian.com",
  "confluence": "atlassian.com",
  "github": "github.com",
  "gitlab": "gitlab.com",
  "hashicorp": "hashicorp.com",
  "terraform": "terraform.io",
  "ansible": "ansible.com",
  "red hat": "redhat.com",
  "redhat": "redhat.com",
  "suse": "suse.com",
  "canonical": "canonical.com",
  "ubuntu": "ubuntu.com",
  "vmware": "vmware.com",
  "dell technologies": "dell.com",
  "dell": "dell.com",
  "hp": "hp.com",
  "hewlett packard": "hp.com",
  "hpe": "hpe.com",
  "hewlett packard enterprise": "hpe.com",
  "lenovo": "lenovo.com",
  "asus": "asus.com",
  "acer": "acer.com",
  "samsung": "samsung.com",
  "lg": "lg.com",
  "sony": "sony.com",
  "panasonic": "panasonic.com",
  "toshiba": "toshiba.com",
  "fujitsu": "fujitsu.com",
  "nec": "nec.com",
  "hitachi": "hitachi.com",
  "sharp": "sharp.com",

  // ── Technology: SaaS / Productivity ──────────────────────────────────────
  "slack": "slack.com",
  "zoom": "zoom.us",
  "microsoft teams": "microsoft.com",
  "notion": "notion.so",
  "airtable": "airtable.com",
  "asana": "asana.com",
  "monday.com": "monday.com",
  "monday": "monday.com",
  "clickup": "clickup.com",
  "linear": "linear.app",
  "figma": "figma.com",
  "canva": "canva.com",
  "miro": "miro.com",
  "lucidchart": "lucidchart.com",
  "loom": "loom.com",
  "intercom": "intercom.com",
  "drift": "drift.com",
  "calendly": "calendly.com",
  "typeform": "typeform.com",
  "surveymonkey": "surveymonkey.com",
  "mailchimp": "mailchimp.com",
  "constant contact": "constantcontact.com",
  "klaviyo": "klaviyo.com",
  "braze": "braze.com",
  "amplitude": "amplitude.com",
  "mixpanel": "mixpanel.com",
  "segment": "segment.com",
  "heap": "heap.io",
  "hotjar": "hotjar.com",
  "fullstory": "fullstory.com",
  "contentsquare": "contentsquare.com",
  "iterable": "iterable.com",
  "sendgrid": "sendgrid.com",
  "postmark": "postmarkapp.com",
  "mailgun": "mailgun.com",
  "webflow": "webflow.com",
  "squarespace": "squarespace.com",
  "wix": "wix.com",
  "shopify": "shopify.com",
  "bigcommerce": "bigcommerce.com",
  "magento": "magento.com",
  "wordpress": "wordpress.com",
  "ghost": "ghost.org",
  "contentful": "contentful.com",
  "sanity": "sanity.io",

  // ── Technology: AI / ML ───────────────────────────────────────────────────
  "openai": "openai.com",
  "anthropic": "anthropic.com",
  "deepmind": "deepmind.com",
  "mistral ai": "mistral.ai",
  "mistral": "mistral.ai",
  "cohere": "cohere.com",
  "hugging face": "huggingface.co",
  "huggingface": "huggingface.co",
  "scale ai": "scale.com",
  "scale": "scale.com",
  "weights and biases": "wandb.ai",
  "wandb": "wandb.ai",
  "replicate": "replicate.com",
  "stability ai": "stability.ai",
  "midjourney": "midjourney.com",
  "runway": "runwayml.com",
  "perplexity": "perplexity.ai",
  "perplexity ai": "perplexity.ai",
  "character.ai": "character.ai",
  "inflection ai": "inflection.ai",
  "adept": "adept.ai",
  "together ai": "together.ai",
  "groq": "groq.com",
  "cerebras": "cerebras.net",

  // ── Technology: Developer Tools / Infrastructure ──────────────────────────
  "vercel": "vercel.com",
  "netlify": "netlify.com",
  "cloudflare": "cloudflare.com",
  "fastly": "fastly.com",
  "akamai": "akamai.com",
  "aws": "aws.amazon.com",
  "amazon web services": "aws.amazon.com",
  "google cloud": "cloud.google.com",
  "microsoft azure": "azure.microsoft.com",
  "azure": "azure.microsoft.com",
  "digital ocean": "digitalocean.com",
  "digitalocean": "digitalocean.com",
  "linode": "linode.com",
  "vultr": "vultr.com",
  "heroku": "heroku.com",
  "render": "render.com",
  "railway": "railway.app",
  "supabase": "supabase.com",
  "firebase": "firebase.google.com",
  "planetscale": "planetscale.com",
  "neon": "neon.tech",
  "cockroachdb": "cockroachlabs.com",
  "redis": "redis.io",
  "confluent": "confluent.io",
  "dbt labs": "getdbt.com",
  "dbt": "getdbt.com",
  "airbyte": "airbyte.com",
  "fivetran": "fivetran.com",
  "stitch": "stitchdata.com",
  "talend": "talend.com",
  "informatica": "informatica.com",
  "mulesoft": "mulesoft.com",
  "boomi": "boomi.com",
  "apigee": "apigee.com",
  "postman": "postman.com",
  "insomnia": "insomnia.rest",

  // ── Technology: Payments & Fintech ────────────────────────────────────────
  "stripe": "stripe.com",
  "paypal": "paypal.com",
  "square": "squareup.com",
  "block": "block.xyz",
  "braintree": "braintreepayments.com",
  "adyen": "adyen.com",
  "checkout.com": "checkout.com",
  "klarna": "klarna.com",
  "affirm": "affirm.com",
  "afterpay": "afterpay.com",
  "sezzle": "sezzle.com",
  "zip": "zip.co",
  "coinbase": "coinbase.com",
  "kraken": "kraken.com",
  "binance": "binance.com",
  "robinhood": "robinhood.com",
  "sofi": "sofi.com",
  "chime": "chime.com",
  "nubank": "nubank.com.br",
  "revolut": "revolut.com",
  "wise": "wise.com",
  "transferwise": "wise.com",
  "monzo": "monzo.com",
  "n26": "n26.com",
  "brex": "brex.com",
  "ramp": "ramp.com",
  "bill.com": "bill.com",
  "bill": "bill.com",
  "plaid": "plaid.com",
  "yodlee": "yodlee.com",
  "marqeta": "marqeta.com",
  "galileo": "galileo-ft.com",
  "nuvei": "nuvei.com",
  "worldpay": "worldpay.com",
  "fiserv": "fiserv.com",
  "fis": "fisglobal.com",
  "jack henry": "jackhenry.com",
  "ncr": "ncr.com",
  "verifone": "verifone.com",
  "ingenico": "ingenico.com",
  "visa": "visa.com",
  "mastercard": "mastercard.com",
  "american express": "americanexpress.com",
  "amex": "americanexpress.com",
  "discover": "discover.com",

  // ── Banking & Financial Services ──────────────────────────────────────────
  "jpmorgan chase": "jpmorganchase.com",
  "jpmorgan": "jpmorgan.com",
  "jp morgan": "jpmorgan.com",
  "jp morgan chase": "jpmorganchase.com",
  "bank of america": "bankofamerica.com",
  "wells fargo": "wellsfargo.com",
  "citigroup": "citigroup.com",
  "citi": "citi.com",
  "citibank": "citibank.com",
  "goldman sachs": "goldmansachs.com",
  "morgan stanley": "morganstanley.com",
  "charles schwab": "schwab.com",
  "schwab": "schwab.com",
  "fidelity": "fidelity.com",
  "fidelity investments": "fidelity.com",
  "vanguard": "vanguard.com",
  "blackrock": "blackrock.com",
  "state street": "statestreet.com",
  "pnc financial": "pnc.com",
  "pnc": "pnc.com",
  "us bancorp": "usbank.com",
  "us bank": "usbank.com",
  "capital one": "capitalone.com",
  "td bank": "td.com",
  "td": "td.com",
  "bmo": "bmo.com",
  "bank of montreal": "bmo.com",
  "royal bank of canada": "rbc.com",
  "rbc": "rbc.com",
  "scotiabank": "scotiabank.com",
  "cibc": "cibc.com",
  "hsbc": "hsbc.com",
  "barclays": "barclays.com",
  "lloyds": "lloyds.com",
  "lloyds banking group": "lloydsbankinggroup.com",
  "natwest": "natwest.com",
  "standard chartered": "sc.com",
  "ubs": "ubs.com",
  "credit suisse": "credit-suisse.com",
  "deutsche bank": "db.com",
  "bnp paribas": "bnpparibas.com",
  "bnp": "bnpparibas.com",
  "societe generale": "societegenerale.com",
  "credit agricole": "credit-agricole.com",
  "ing": "ing.com",
  "santander": "santander.com",
  "bbva": "bbva.com",
  "unicredit": "unicredit.eu",
  "intesa sanpaolo": "intesasanpaolo.com",
  "nordea": "nordea.com",
  "danske bank": "danskebank.com",
  "handelsbanken": "handelsbanken.se",
  "seb": "sebgroup.com",
  "commerzbank": "commerzbank.com",
  "rabobank": "rabobank.com",
  "abn amro": "abnamro.com",
  "mufg": "mufg.jp",
  "mitsubishi ufj": "mufg.jp",
  "smbc": "smbc.co.jp",
  "sumitomo mitsui": "smbc.co.jp",
  "mizuho": "mizuho-fg.com",
  "nomura": "nomura.com",
  "daiwa": "daiwa.jp",
  "icbc": "icbc.com.cn",
  "china construction bank": "ccb.com",
  "bank of china": "boc.cn",
  "agricultural bank of china": "abchina.com",
  "axis bank": "axisbank.com",
  "hdfc bank": "hdfcbank.com",
  "hdfc": "hdfc.com",
  "icici bank": "icicibank.com",
  "icici": "icicibank.com",
  "sbi": "onlinesbi.com",
  "state bank of india": "onlinesbi.com",
  "itau": "itau.com.br",
  "bradesco": "bradesco.com.br",
  "lazard": "lazard.com",
  "evercore": "evercore.com",
  "jefferies": "jefferies.com",
  "raymond james": "raymondjames.com",
  "edward jones": "edwardjones.com",
  "ameriprise": "ameriprise.com",
  "principal financial": "principal.com",
  "principal": "principal.com",
  "lincoln financial": "lfg.com",
  "hartford": "thehartford.com",
  "the hartford": "thehartford.com",
  "prudential": "prudential.com",
  "metlife": "metlife.com",
  "aig": "aig.com",
  "american international group": "aig.com",
  "allstate": "allstate.com",
  "progressive": "progressive.com",
  "travelers": "travelers.com",
  "chubb": "chubb.com",
  "markel": "markel.com",
  "berkshire hathaway": "berkshirehathaway.com",
  "t rowe price": "troweprice.com",
  "t. rowe price": "troweprice.com",
  "invesco": "invesco.com",
  "franklin templeton": "franklintempleton.com",
  "pimco": "pimco.com",
  "kkr": "kkr.com",
  "carlyle group": "carlyle.com",
  "carlyle": "carlyle.com",
  "apollo global": "apollo.com",
  "apollo": "apollo.com",
  "blackstone": "blackstone.com",
  "tpg": "tpg.com",
  "warburg pincus": "warburgpincus.com",
  "sequoia capital": "sequoiacap.com",
  "sequoia": "sequoiacap.com",
  "andreessen horowitz": "a16z.com",
  "a16z": "a16z.com",
  "benchmark": "benchmark.com",
  "accel": "accel.com",
  "greylock": "greylock.com",
  "kleiner perkins": "kleinerperkins.com",
  "lightspeed venture partners": "lsvp.com",
  "general atlantic": "generalatlantic.com",
  "tiger global": "tigerglobal.com",
  "coatue": "coatue.com",
  "insight partners": "insightpartners.com",

  // ── Retail & E-Commerce ───────────────────────────────────────────────────
  "walmart": "walmart.com",
  "costco": "costco.com",
  "target": "target.com",
  "kroger": "kroger.com",
  "home depot": "homedepot.com",
  "lowe's": "lowes.com",
  "lowes": "lowes.com",
  "walgreens": "walgreens.com",
  "cvs": "cvs.com",
  "cvs health": "cvshealth.com",
  "rite aid": "riteaid.com",
  "dollar general": "dollargeneral.com",
  "dollar tree": "dollartree.com",
  "family dollar": "familydollar.com",
  "five below": "fivebelow.com",
  "tjx": "tjx.com",
  "tj maxx": "tjmaxx.com",
  "marshall's": "marshalls.com",
  "marshalls": "marshalls.com",
  "ross stores": "rossstores.com",
  "ross": "rossstores.com",
  "nordstrom": "nordstrom.com",
  "macy's": "macys.com",
  "macys": "macys.com",
  "bloomingdale's": "bloomingdales.com",
  "bloomingdales": "bloomingdales.com",
  "neiman marcus": "neimanmarcus.com",
  "saks fifth avenue": "saksfifthavenue.com",
  "saks": "saksfifthavenue.com",
  "kohl's": "kohls.com",
  "kohls": "kohls.com",
  "jcpenney": "jcpenney.com",
  "gap": "gap.com",
  "banana republic": "bananarepublic.com",
  "old navy": "oldnavy.com",
  "athleta": "athleta.com",
  "h&m": "hm.com",
  "hm": "hm.com",
  "zara": "zara.com",
  "inditex": "inditex.com",
  "uniqlo": "uniqlo.com",
  "fast retailing": "fastretailing.com",
  "primark": "primark.com",
  "marks and spencer": "marksandspencer.com",
  "marks & spencer": "marksandspencer.com",
  "next": "next.co.uk",
  "john lewis": "johnlewis.com",
  "waitrose": "waitrose.com",
  "tesco": "tesco.com",
  "sainsbury's": "sainsburys.co.uk",
  "sainsburys": "sainsburys.co.uk",
  "asda": "asda.com",
  "lidl": "lidl.com",
  "aldi": "aldi.com",
  "carrefour": "carrefour.com",
  "ikea": "ikea.com",
  "metro": "metro.de",
  "rewe": "rewe.de",
  "edeka": "edeka.de",
  "alibaba": "alibaba.com",
  "aliexpress": "aliexpress.com",
  "taobao": "taobao.com",
  "tmall": "tmall.com",
  "jd.com": "jd.com",
  "jd": "jd.com",
  "pinduoduo": "pinduoduo.com",
  "temu": "temu.com",
  "shein": "shein.com",
  "ebay": "ebay.com",
  "etsy": "etsy.com",
  "wayfair": "wayfair.com",
  "overstock": "overstock.com",
  "chewy": "chewy.com",
  "petco": "petco.com",
  "petsmart": "petsmart.com",
  "bed bath and beyond": "bedbathandbeyond.com",
  "best buy": "bestbuy.com",
  "gamestop": "gamestop.com",
  "radioshack": "radioshack.com",
  "autozone": "autozone.com",
  "o'reilly auto parts": "oreillyauto.com",
  "advance auto parts": "advanceautoparts.com",
  "napa auto parts": "napaonline.com",
  "tractor supply": "tractorsupply.com",
  "ace hardware": "acehardware.com",
  "true value": "truevalue.com",
  "dick's sporting goods": "dickssportinggoods.com",
  "bass pro shops": "basspro.com",
  "cabela's": "cabelas.com",
  "rei": "rei.com",
  "lululemon": "lululemon.com",
  "under armour": "underarmour.com",
  "nike": "nike.com",
  "adidas": "adidas.com",
  "puma": "puma.com",
  "new balance": "newbalance.com",
  "asics": "asics.com",
  "reebok": "reebok.com",
  "skechers": "skechers.com",
  "vans": "vans.com",
  "converse": "converse.com",
  "timberland": "timberland.com",
  "dr. martens": "drmartens.com",
  "ugg": "ugg.com",
  "crocs": "crocs.com",
  "foot locker": "footlocker.com",
  "finish line": "finishline.com",
  "champs sports": "champssports.com",
  "ralph lauren": "ralphlauren.com",
  "tommy hilfiger": "tommy.com",
  "calvin klein": "calvinklein.com",
  "michael kors": "michaelkors.com",
  "kate spade": "katespade.com",
  "coach": "coach.com",
  "tapestry": "tapestry.com",
  "capri holdings": "capriholdings.com",
  "versace": "versace.com",
  "gucci": "gucci.com",
  "louis vuitton": "louisvuitton.com",
  "lvmh": "lvmh.com",
  "hermes": "hermes.com",
  "chanel": "chanel.com",
  "prada": "prada.com",
  "burberry": "burberry.com",
  "dior": "dior.com",
  "armani": "armani.com",
  "hugo boss": "hugoboss.com",
  "hugo boss ag": "hugoboss.com",
  "ferragamo": "ferragamo.com",
  "tod's": "tods.com",
  "richemont": "richemont.com",
  "cartier": "cartier.com",
  "tiffany": "tiffany.com",
  "pandora": "pandora.net",
  "swatch": "swatch.com",
  "rolex": "rolex.com",
  "omega": "omegawatches.com",
  "tag heuer": "tagheuer.com",
  "longines": "longines.com",

  // ── Automotive ────────────────────────────────────────────────────────────
  "tesla": "tesla.com",
  "ford": "ford.com",
  "general motors": "gm.com",
  "gm": "gm.com",
  "chevrolet": "chevrolet.com",
  "cadillac": "cadillac.com",
  "buick": "buick.com",
  "gmc": "gmc.com",
  "stellantis": "stellantis.com",
  "chrysler": "chrysler.com",
  "dodge": "dodge.com",
  "jeep": "jeep.com",
  "ram": "ramtrucks.com",
  "fiat": "fiat.com",
  "alfa romeo": "alfaromeo.com",
  "maserati": "maserati.com",
  "toyota": "toyota.com",
  "honda": "honda.com",
  "nissan": "nissan.com",
  "subaru": "subaru.com",
  "mazda": "mazda.com",
  "mitsubishi motors": "mitsubishicars.com",
  "mitsubishi": "mitsubishi.com",
  "lexus": "lexus.com",
  "infiniti": "infinitiusa.com",
  "acura": "acura.com",
  "volkswagen": "vw.com",
  "vw": "vw.com",
  "audi": "audi.com",
  "bmw": "bmw.com",
  "mercedes-benz": "mercedes-benz.com",
  "mercedes": "mercedes-benz.com",
  "porsche": "porsche.com",
  "land rover": "landrover.com",
  "jaguar": "jaguar.com",
  "volvo": "volvocars.com",
  "peugeot": "peugeot.com",
  "renault": "renault.com",
  "citroën": "citroen.com",
  "citroen": "citroen.com",
  "opel": "opel.com",
  "vauxhall": "vauxhall.co.uk",
  "seat": "seat.com",
  "skoda": "skoda-auto.com",
  "ferrari": "ferrari.com",
  "lamborghini": "lamborghini.com",
  "bugatti": "bugatti.com",
  "bentley": "bentleymotors.com",
  "rolls-royce": "rolls-roycemotorcars.com",
  "rolls royce": "rolls-roycemotorcars.com",
  "mclaren": "mclaren.com",
  "aston martin": "astonmartin.com",
  "hyundai": "hyundai.com",
  "kia": "kia.com",
  "genesis": "genesis.com",
  "rivian": "rivian.com",
  "lucid motors": "lucidmotors.com",
  "lucid": "lucidmotors.com",
  "fisker": "fiskerinc.com",
  "nio": "nio.com",
  "byd": "byd.com",
  "xpeng": "xpeng.com",
  "li auto": "lixiang.com",
  "harley-davidson": "harley-davidson.com",
  "harley davidson": "harley-davidson.com",
  "deere": "deere.com",
  "john deere": "deere.com",
  "caterpillar": "caterpillar.com",

  // ── Aerospace & Defense ───────────────────────────────────────────────────
  "boeing": "boeing.com",
  "airbus": "airbus.com",
  "lockheed martin": "lockheedmartin.com",
  "lockheed": "lockheedmartin.com",
  "raytheon": "rtx.com",
  "rtx": "rtx.com",
  "northrop grumman": "northropgrumman.com",
  "northrop": "northropgrumman.com",
  "general dynamics": "gd.com",
  "l3harris": "l3harris.com",
  "leidos": "leidos.com",
  "booz allen hamilton": "boozallen.com",
  "booz allen": "boozallen.com",
  "saic": "saic.com",
  "bae systems": "baesystems.com",
  "bae": "baesystems.com",
  "rolls-royce holdings": "rolls-royce.com",
  "thales": "thalesgroup.com",
  "safran": "safran-group.com",
  "leonardo": "leonardo.com",
  "dassault": "dassault-aviation.com",
  "spacex": "spacex.com",
  "blue origin": "blueorigin.com",
  "rocket lab": "rocketlabusa.com",
  "virgin galactic": "virgingalactic.com",
  "sierra space": "sierraspace.com",

  // ── Energy & Utilities ────────────────────────────────────────────────────
  "exxon mobil": "exxonmobil.com",
  "exxonmobil": "exxonmobil.com",
  "exxon": "exxonmobil.com",
  "chevron": "chevron.com",
  "shell": "shell.com",
  "bp": "bp.com",
  "british petroleum": "bp.com",
  "totalenergies": "totalenergies.com",
  "total": "totalenergies.com",
  "conocophillips": "conocophillips.com",
  "conoco": "conocophillips.com",
  "marathon petroleum": "marathonpetroleum.com",
  "valero": "valero.com",
  "phillips 66": "phillips66.com",
  "pioneer natural resources": "pxd.com",
  "devon energy": "devonenergy.com",
  "eog resources": "eogresources.com",
  "hess": "hess.com",
  "apa corporation": "apacorporation.com",
  "diamondback energy": "diamondbackenergy.com",
  "occidental": "oxy.com",
  "oxy": "oxy.com",
  "halliburton": "halliburton.com",
  "schlumberger": "slb.com",
  "slb": "slb.com",
  "baker hughes": "bakerhughes.com",
  "williams companies": "williams.com",
  "oneok": "oneok.com",
  "kinder morgan": "kindermorgan.com",
  "enterprise products": "enterpriseproducts.com",
  "nextera energy": "nexteraenergy.com",
  "nextera": "nexteraenergy.com",
  "duke energy": "duke-energy.com",
  "duke": "duke-energy.com",
  "southern company": "southerncompany.com",
  "dominion energy": "dominionenergy.com",
  "dominion": "dominionenergy.com",
  "american electric power": "aep.com",
  "aep": "aep.com",
  "exelon": "exeloncorp.com",
  "constellation energy": "constellationenergy.com",
  "pge": "pge.com",
  "pacific gas electric": "pge.com",
  "sce": "sce.com",
  "con edison": "coned.com",
  "entergy": "entergy.com",
  "enel": "enel.com",
  "engie": "engie.com",
  "rwe": "rwe.com",
  "eon": "eon.com",
  "e.on": "eon.com",
  "vattenfall": "vattenfall.com",
  "equinor": "equinor.com",
  "petrobras": "petrobras.com.br",
  "aramco": "aramco.com",
  "saudi aramco": "aramco.com",
  "adnoc": "adnoc.ae",
  "petrochina": "petrochina.com.cn",
  "sinopec": "sinopec.com",
  "gazprom": "gazprom.com",
  "rosneft": "rosneft.com",
  "basf": "basf.com",
  "dow": "dow.com",
  "dupont": "dupont.com",
  "lyondellbasell": "lyondellbasell.com",
  "eastman chemical": "eastman.com",
  "eastman": "eastman.com",
  "celanese": "celanese.com",
  "olin": "olin.com",
  "air products": "airproducts.com",
  "linde": "linde.com",
  "air liquide": "airliquide.com",
  "praxair": "praxair.com",

  // ── Healthcare & Pharmaceuticals ──────────────────────────────────────────
  "johnson & johnson": "jnj.com",
  "johnson and johnson": "jnj.com",
  "j&j": "jnj.com",
  "pfizer": "pfizer.com",
  "merck": "merck.com",
  "abbvie": "abbvie.com",
  "eli lilly": "lilly.com",
  "lilly": "lilly.com",
  "bristol-myers squibb": "bms.com",
  "bristol myers squibb": "bms.com",
  "bms": "bms.com",
  "amgen": "amgen.com",
  "gilead sciences": "gilead.com",
  "gilead": "gilead.com",
  "biogen": "biogen.com",
  "regeneron": "regeneron.com",
  "moderna": "modernatx.com",
  "biontech": "biontech.com",
  "astrazeneca": "astrazeneca.com",
  "roche": "roche.com",
  "novartis": "novartis.com",
  "sanofi": "sanofi.com",
  "gsk": "gsk.com",
  "glaxosmithkline": "gsk.com",
  "bayer": "bayer.com",
  "novo nordisk": "novonordisk.com",
  "novo": "novonordisk.com",
  "takeda": "takeda.com",
  "daiichi sankyo": "daiichisankyo.com",
  "astellas": "astellas.com",
  "eisai": "eisai.com",
  "ucb": "ucb.com",
  "ipsen": "ipsen.com",
  "alexion": "alexion.com",
  "vertex pharmaceuticals": "vrtx.com",
  "vertex": "vrtx.com",
  "iqvia": "iqvia.com",
  "quintiles": "iqvia.com",
  "covance": "covance.com",
  "labcorp": "labcorp.com",
  "quest diagnostics": "questdiagnostics.com",
  "quest": "questdiagnostics.com",
  "medtronic": "medtronic.com",
  "stryker": "stryker.com",
  "boston scientific": "bostonscientific.com",
  "edwards lifesciences": "edwards.com",
  "edwards": "edwards.com",
  "becton dickinson": "bd.com",
  "bd": "bd.com",
  "zimmer biomet": "zimmerbiomet.com",
  "zimmer": "zimmerbiomet.com",
  "smith & nephew": "smith-nephew.com",
  "hologic": "hologic.com",
  "danaher": "danaher.com",
  "thermo fisher": "thermofisher.com",
  "thermo fisher scientific": "thermofisher.com",
  "agilent": "agilent.com",
  "bio-rad": "bio-rad.com",
  "waters corporation": "waters.com",
  "illumina": "illumina.com",
  "10x genomics": "10xgenomics.com",
  "pacific biosciences": "pacb.com",
  "unitedhealth": "unitedhealthgroup.com",
  "unitedhealth group": "unitedhealthgroup.com",
  "united health": "unitedhealthgroup.com",
  "anthem": "anthem.com",
  "elevance health": "elevancehealth.com",
  "elevance": "elevancehealth.com",
  "cigna": "cigna.com",
  "aetna": "aetna.com",
  "humana": "humana.com",
  "centene": "centene.com",
  "molina healthcare": "molinahealthcare.com",
  "molina": "molinahealthcare.com",
  "hca healthcare": "hcahealthcare.com",
  "hca": "hcahealthcare.com",
  "tenet healthcare": "tenethealth.com",
  "community health systems": "chs.net",
  "ascension": "ascension.org",
  "kaiser permanente": "kaiserpermanente.org",
  "kaiser": "kaiserpermanente.org",
  "mayo clinic": "mayoclinic.org",
  "mayo": "mayoclinic.org",
  "cleveland clinic": "clevelandclinic.org",
  "johns hopkins": "hopkinsmedicine.org",
  "mass general": "massgeneral.org",
  "henry ford health": "henryford.com",
  "banner health": "bannerhealth.com",
  "providence": "providence.org",
  "adventhealth": "adventhealth.com",

  // ── Consulting & Professional Services ───────────────────────────────────
  "mckinsey": "mckinsey.com",
  "mckinsey & company": "mckinsey.com",
  "bcg": "bcg.com",
  "boston consulting group": "bcg.com",
  "bain": "bain.com",
  "bain & company": "bain.com",
  "deloitte": "deloitte.com",
  "pwc": "pwc.com",
  "pricewaterhousecoopers": "pwc.com",
  "ernst & young": "ey.com",
  "ey": "ey.com",
  "kpmg": "kpmg.com",
  "accenture": "accenture.com",
  "oliver wyman": "oliverwyman.com",
  "roland berger": "rolandberger.com",
  "a.t. kearney": "kearney.com",
  "kearney": "kearney.com",
  "strategy&": "strategyand.pwc.com",
  "booz & company": "strategyand.pwc.com",
  "gartner": "gartner.com",
  "forrester": "forrester.com",
  "idc": "idc.com",
  "capgemini": "capgemini.com",
  "infosys": "infosys.com",
  "tata consultancy services": "tcs.com",
  "tcs": "tcs.com",
  "wipro": "wipro.com",
  "hcl technologies": "hcltech.com",
  "hcl": "hcltech.com",
  "cognizant": "cognizant.com",
  "tech mahindra": "techmahindra.com",
  "mphasis": "mphasis.com",
  "l&t technology services": "ltts.com",
  "ltts": "ltts.com",
  "unisys": "unisys.com",
  "dxc technology": "dxc.com",
  "dxc": "dxc.com",
  "cgi": "cgi.com",
  "atos": "atos.net",
  "indra": "indracompany.com",
  "sopra steria": "soprasteria.com",
  "bureau veritas": "bureauveritas.com",
  "manpower group": "manpowergroup.com",
  "manpower": "manpower.com",
  "adecco": "adecco.com",
  "randstad": "randstad.com",
  "robert half": "roberthalf.com",
  "kelly services": "kellyservices.com",
  "aon": "aon.com",
  "marsh mclennan": "marshmclennan.com",
  "marsh & mclennan": "marshmclennan.com",
  "willis towers watson": "wtwco.com",
  "wtw": "wtwco.com",
  "gallagher": "ajg.com",
  "arthur j gallagher": "ajg.com",
  "ice": "intercontinentalexchange.com",
  "intercontinental exchange": "intercontinentalexchange.com",
  "nasdaq": "nasdaq.com",
  "nyse": "nyse.com",
  "london stock exchange": "lseg.com",
  "lseg": "lseg.com",
  "cboe": "cboe.com",
  "cme group": "cmegroup.com",
  "cme": "cmegroup.com",
  "dtcc": "dtcc.com",
  "s&p global": "spglobal.com",
  "sp global": "spglobal.com",
  "moody's": "moodys.com",
  "moodys": "moodys.com",
  "fitch ratings": "fitchratings.com",
  "fitch": "fitchratings.com",
  "msci": "msci.com",

  // ── Telecom ───────────────────────────────────────────────────────────────
  "at&t": "att.com",
  "att": "att.com",
  "verizon": "verizon.com",
  "t-mobile": "t-mobile.com",
  "tmobile": "t-mobile.com",
  "sprint": "sprint.com",
  "comcast": "comcast.com",
  "xfinity": "xfinity.com",
  "charter communications": "charter.com",
  "spectrum": "spectrum.com",
  "cox communications": "cox.com",
  "cox": "cox.com",
  "dish network": "dish.com",
  "dish": "dish.com",
  "directv": "directv.com",
  "lumen technologies": "lumen.com",
  "centurylink": "centurylink.com",
  "frontier communications": "frontier.com",
  "windstream": "windstream.com",
  "cincinnati bell": "altafiber.com",
  "altafiber": "altafiber.com",
  "vodafone": "vodafone.com",
  "telefonica": "telefonica.com",
  "orange": "orange.com",
  "deutsche telekom": "telekom.com",
  "telekom": "telekom.com",
  "swisscom": "swisscom.ch",
  "bt": "bt.com",
  "bt group": "bt.com",
  "sky": "sky.com",
  "telia": "telia.com",
  "proximus": "proximus.com",
  "belgacom": "proximus.com",
  "telenor": "telenor.com",
  "dtac": "dtac.co.th",
  "singtel": "singtel.com",
  "telstra": "telstra.com.au",
  "ntt": "ntt.com",
  "softbank": "softbank.jp",
  "kddi": "kddi.com",
  "docomo": "docomo.com",
  "ntt docomo": "docomo.com",
  "china telecom": "chinatelecom.com.cn",
  "china mobile": "chinamobileltd.com",
  "china unicom": "chinaunicom.com.cn",
  "bharti airtel": "airtel.in",
  "airtel": "airtel.in",
  "reliance jio": "jio.com",
  "jio": "jio.com",
  "vivo": "vivo.com.br",
  "claro": "claro.com",
  "rogers": "rogers.com",
  "telus": "telus.com",
  "bell canada": "bell.ca",
  "bell": "bell.ca",
  "shaw": "shaw.ca",
  "videotron": "videotron.com",

  // ── Media & Entertainment ─────────────────────────────────────────────────
  "disney": "disney.com",
  "the walt disney company": "thewaltdisneycompany.com",
  "walt disney": "disney.com",
  "warner bros": "warnerbros.com",
  "warner brothers": "warnerbros.com",
  "warner bros discovery": "wbd.com",
  "wbd": "wbd.com",
  "discovery": "discovery.com",
  "nbcuniversal": "nbcuniversal.com",
  "nbc": "nbc.com",
  "universal pictures": "universalpictures.com",
  "comcast nbcuniversal": "comcast.com",
  "paramount": "paramount.com",
  "paramount global": "paramount.com",
  "cbs": "cbs.com",
  "showtime": "sho.com",
  "fox corporation": "foxcorporation.com",
  "fox": "foxcorporation.com",
  "fox news": "foxnews.com",
  "news corp": "newscorp.com",
  "wall street journal": "wsj.com",
  "wsj": "wsj.com",
  "new york times": "nytimes.com",
  "nyt": "nytimes.com",
  "washington post": "washingtonpost.com",
  "financial times": "ft.com",
  "ft": "ft.com",
  "the economist": "economist.com",
  "bloomberg": "bloomberg.com",
  "reuters": "reuters.com",
  "associated press": "apnews.com",
  "ap": "apnews.com",
  "bbc": "bbc.com",
  "cnn": "cnn.com",
  "msnbc": "msnbc.com",
  "viacom": "viacom.com",
  "mtv": "mtv.com",
  "nickelodeon": "nick.com",
  "vh1": "vh1.com",
  "comedy central": "cc.com",
  "amc networks": "amcnetworks.com",
  "amc": "amc.com",
  "hbo": "hbo.com",
  "max": "max.com",
  "hulu": "hulu.com",
  "peacock": "peacocktv.com",
  "apple tv": "apple.com",
  "apple tv+": "apple.com",
  "amazon prime video": "amazon.com",
  "paramount+": "paramountplus.com",
  "paramount plus": "paramountplus.com",
  "disney+": "disneyplus.com",
  "disney plus": "disneyplus.com",
  "youtube": "youtube.com",
  "twitch": "twitch.tv",
  "tiktok": "tiktok.com",
  "bytedance": "bytedance.com",
  "instagram": "instagram.com",
  "snapchat": "snapchat.com",
  "snap": "snap.com",
  "pinterest": "pinterest.com",
  "linkedin": "linkedin.com",
  "twitter": "twitter.com",
  "x": "x.com",
  "reddit": "reddit.com",
  "tumblr": "tumblr.com",
  "quora": "quora.com",
  "medium": "medium.com",
  "substack": "substack.com",
  "iheartmedia": "iheartmedia.com",
  "cumulus media": "cumulusmedia.com",
  "audacy": "audacy.com",
  "sirius xm": "siriusxm.com",
  "siriusxm": "siriusxm.com",
  "pandora music": "pandora.com",
  "spotify": "spotify.com",
  "apple music": "apple.com",
  "tidal": "tidal.com",
  "deezer": "deezer.com",
  "soundcloud": "soundcloud.com",
  "live nation": "livenationentertainment.com",
  "ticketmaster": "ticketmaster.com",
  "aeg": "aegpresents.com",
  "anschutz entertainment": "aegpresents.com",
  "wwe": "wwe.com",
  "ufc": "ufc.com",
  "endeavor": "endeavorco.com",
  "img": "img.com",
  "william morris endeavor": "wmeagency.com",
  "ume": "umusic.com",
  "universal music group": "universalmusic.com",
  "warner music": "wmg.com",
  "sony music": "sonymusic.com",
  "sony entertainment": "sony.com",
  "playstation": "playstation.com",
  "xbox": "xbox.com",
  "nintendo": "nintendo.com",
  "activision blizzard": "activisionblizzard.com",
  "activision": "activision.com",
  "blizzard": "blizzard.com",
  "electronic arts": "ea.com",
  "ea": "ea.com",
  "ubisoft": "ubisoft.com",
  "take-two interactive": "take2games.com",
  "take two": "take2games.com",
  "2k games": "2k.com",
  "2k": "2k.com",
  "rockstar games": "rockstargames.com",
  "valve": "valvesoftware.com",
  "steam": "store.steampowered.com",
  "epic games": "epicgames.com",
  "epic": "epicgames.com",
  "unity": "unity.com",
  "unity technologies": "unity.com",
  "roblox": "roblox.com",
  "riot games": "riotgames.com",
  "tencent games": "tencent.com",
  "tencent": "tencent.com",
  "netease": "netease.com",
  "nexon": "nexon.com",
  "ncsoft": "ncsoft.com",
  "square enix": "square-enix.com",
  "capcom": "capcom.com",
  "konami": "konami.com",
  "sega": "sega.com",
  "bandai namco": "bandainamcoent.com",
  "bandai": "bandai.com",

  // ── Food & Beverage ───────────────────────────────────────────────────────
  "mcdonald's": "mcdonalds.com",
  "mcdonalds": "mcdonalds.com",
  "starbucks": "starbucks.com",
  "subway": "subway.com",
  "chick-fil-a": "chick-fil-a.com",
  "chick fil a": "chick-fil-a.com",
  "taco bell": "tacobell.com",
  "burger king": "bk.com",
  "wendy's": "wendys.com",
  "wendys": "wendys.com",
  "domino's": "dominos.com",
  "dominos": "dominos.com",
  "pizza hut": "pizzahut.com",
  "papa john's": "papajohns.com",
  "papa johns": "papajohns.com",
  "kfc": "kfc.com",
  "popeyes": "popeyes.com",
  "dunkin": "dunkindonuts.com",
  "dunkin donuts": "dunkindonuts.com",
  "panera bread": "panerabread.com",
  "panera": "panerabread.com",
  "chipotle": "chipotle.com",
  "shake shack": "shakeshack.com",
  "in-n-out": "in-n-out.com",
  "in-n-out burger": "in-n-out.com",
  "five guys": "fiveguys.com",
  "sonic": "sonicdrivein.com",
  "dairy queen": "dairyqueen.com",
  "ihop": "ihop.com",
  "denny's": "dennys.com",
  "dennys": "dennys.com",
  "applebee's": "applebees.com",
  "applebees": "applebees.com",
  "olive garden": "olivegarden.com",
  "red lobster": "redlobster.com",
  "outback steakhouse": "outback.com",
  "darden restaurants": "darden.com",
  "darden": "darden.com",
  "yum! brands": "yum.com",
  "yum brands": "yum.com",
  "restaurant brands international": "rbi.com",
  "rbi": "rbi.com",
  "mcdonald's corporation": "mcdonalds.com",
  "nestle": "nestle.com",
  "unilever": "unilever.com",
  "kraft heinz": "kraftheinzcompany.com",
  "kraft": "kraftfoods.com",
  "heinz": "heinz.com",
  "mondelez": "mondelezinternational.com",
  "oreo": "oreo.com",
  "nabisco": "nabisco.com",
  "kellogg's": "kelloggs.com",
  "kelloggs": "kelloggs.com",
  "kellanova": "kellanova.com",
  "general mills": "generalmills.com",
  "campbell's": "campbells.com",
  "campbells": "campbells.com",
  "conagra": "conagrabrands.com",
  "conagra brands": "conagrabrands.com",
  "hormel": "hormel.com",
  "tyson foods": "tysonfoods.com",
  "tyson": "tysonfoods.com",
  "jbs": "jbs.com.br",
  "smithfield foods": "smithfieldfoods.com",
  "smithfield": "smithfieldfoods.com",
  "perdue": "perdue.com",
  "pilgrim's pride": "pilgrims.com",
  "cargill": "cargill.com",
  "archer daniels midland": "adm.com",
  "adm": "adm.com",
  "bunge": "bunge.com",
  "louis dreyfus": "ldcom.com",
  "pepsico": "pepsico.com",
  "pepsi": "pepsi.com",
  "coca-cola": "coca-cola.com",
  "coca cola": "coca-cola.com",
  "dr pepper": "drpepper.com",
  "keurig dr pepper": "keurigdrpepper.com",
  "monster beverage": "monsterbevcorp.com",
  "monster": "monsterenergy.com",
  "red bull": "redbull.com",
  "anheuser-busch": "anheuser-busch.com",
  "anheuser busch": "anheuser-busch.com",
  "ab inbev": "ab-inbev.com",
  "budweiser": "budweiser.com",
  "molson coors": "molsoncoors.com",
  "heineken": "heineken.com",
  "carlsberg": "carlsberg.com",
  "diageo": "diageo.com",
  "pernod ricard": "pernod-ricard.com",
  "constellation brands": "cbrands.com",
  "brown-forman": "brown-forman.com",
  "jack daniel's": "jackdaniels.com",
  "bacardi": "bacardi.com",
  "beam suntory": "beamsuntory.com",
  "danaone": "danone.com",
  "danone": "danone.com",
  "lactalis": "lactalis.com",
  "arla foods": "arlafoods.com",
  "bel group": "groupe-bel.com",
  "saputo": "saputo.com",
  "fonterra": "fonterra.com",
  "meiji": "meiji.co.jp",
  "ajinomoto": "ajinomoto.com",
  "kirin": "kirin.co.jp",
  "asahi": "asahi.com",
  "suntory": "suntory.com",
  "mars": "mars.com",
  "ferrero": "ferrero.com",
  "lindt": "lindt.com",
  "godiva": "godiva.com",
  "hershey": "thehersheycompany.com",
  "the hershey company": "thehersheycompany.com",

  // ── Transportation & Logistics ────────────────────────────────────────────
  "ups": "ups.com",
  "fedex": "fedex.com",
  "dhl": "dhl.com",
  "usps": "usps.com",
  "united states postal service": "usps.com",
  "xpo logistics": "xpo.com",
  "xpo": "xpo.com",
  "ch robinson": "chrobinson.com",
  "c.h. robinson": "chrobinson.com",
  "j.b. hunt": "jbhunt.com",
  "jb hunt": "jbhunt.com",
  "werner enterprises": "werner.com",
  "schneider national": "schneider.com",
  "old dominion": "odfl.com",
  "freight": "odfl.com",
  "estes express": "estes-express.com",
  "saia": "saia.com",
  "abf freight": "abf.com",
  "freight ways": "abf.com",
  "maersk": "maersk.com",
  "msc": "msc.com",
  "cma cgm": "cma-cgm.com",
  "cosco": "cosco.com",
  "hapag-lloyd": "hapag-lloyd.com",
  "evergreen": "evergreen-marine.com",
  "yang ming": "yangming.com",
  "one": "one-line.com",
  "hyundai merchant marine": "hmm21.com",
  "hmm": "hmm21.com",
  "emirates logistics": "emirateslogistics.com",
  "dubai ports world": "dpworld.com",
  "dpworld": "dpworld.com",
  "panalpina": "panalpina.com",
  "kuehne nagel": "kuehne-nagel.com",
  "kühne nagel": "kuehne-nagel.com",
  "db schenker": "dbschenker.com",
  "expeditors": "expeditors.com",
  "american airlines": "aa.com",
  "aa": "aa.com",
  "united airlines": "united.com",
  "united": "united.com",
  "delta": "delta.com",
  "delta air lines": "delta.com",
  "southwest airlines": "southwest.com",
  "southwest": "southwest.com",
  "alaska airlines": "alaskaair.com",
  "alaska air": "alaskaair.com",
  "jetblue": "jetblue.com",
  "spirit airlines": "spirit.com",
  "frontier airlines": "flyfrontier.com",
  "lufthansa": "lufthansa.com",
  "british airways": "britishairways.com",
  "air france": "airfrance.com",
  "klm": "klm.com",
  "air france klm": "airfranceklm.com",
  "emirates": "emirates.com",
  "etihad": "etihad.com",
  "qatar airways": "qatarairways.com",
  "singapore airlines": "singaporeair.com",
  "cathay pacific": "cathaypacific.com",
  "ana": "ana.co.jp",
  "all nippon airways": "ana.co.jp",
  "japan airlines": "jal.com",
  "jal": "jal.com",
  "korean air": "koreanair.com",
  "asiana": "flyasiana.com",
  "ryanair": "ryanair.com",
  "easyjet": "easyjet.com",
  "wizz air": "wizzair.com",
  "turkish airlines": "turkishairlines.com",
  "iberia": "iberia.com",
  "tap air portugal": "tapairportugal.com",
  "air canada": "aircanada.com",
  "westjet": "westjet.com",
  "qantas": "qantas.com",
  "virgin australia": "virginaustralia.com",
  "virgin atlantic": "virginatlantic.com",
  "hertz": "hertz.com",
  "enterprise": "enterprise.com",
  "enterprise rent-a-car": "enterprise.com",
  "avis": "avis.com",
  "budget": "budget.com",
  "national car rental": "nationalcar.com",
  "alamo": "alamo.com",
  "sixt": "sixt.com",
  "europcar": "europcar.com",
  "uber": "uber.com",
  "lyft": "lyft.com",
  "grab": "grab.com",
  "gojek": "gojek.com",
  "ola": "olacabs.com",
  "didi": "didiglobal.com",
  "bolt": "bolt.eu",
  "free now": "free-now.com",
  "cabify": "cabify.com",
  "doordash": "doordash.com",
  "grubhub": "grubhub.com",
  "uber eats": "ubereats.com",
  "instacart": "instacart.com",
  "shipt": "shipt.com",
  "gopuff": "gopuff.com",
  "rappi": "rappi.com",

  // ── Real Estate ───────────────────────────────────────────────────────────
  "cbre": "cbre.com",
  "jones lang lasalle": "jll.com",
  "jll": "jll.com",
  "cushman wakefield": "cushmanwakefield.com",
  "cushman & wakefield": "cushmanwakefield.com",
  "colliers": "colliers.com",
  "newmark": "nmrk.com",
  "savills": "savills.com",
  "knight frank": "knightfrank.com",
  "redfin": "redfin.com",
  "zillow": "zillow.com",
  "realtor.com": "realtor.com",
  "trulia": "trulia.com",
  "compass": "compass.com",
  "keller williams": "kw.com",
  "re/max": "remax.com",
  "remax": "remax.com",
  "century 21": "century21.com",
  "coldwell banker": "coldwellbanker.com",
  "sotheby's realty": "sothebysrealty.com",
  "berkshire hathaway homeservices": "bhhsnorcalrealty.com",
  "prologis": "prologis.com",
  "simon property group": "simon.com",
  "simon property": "simon.com",
  "equinix": "equinix.com",
  "digital realty": "digitalrealty.com",
  "iron mountain": "ironmountain.com",
  "public storage": "publicstorage.com",
  "extra space storage": "extraspace.com",
  "life storage": "lifestorage.com",
  "weyerhaeuser": "weyerhaeuser.com",
  "brookfield": "brookfield.com",
  "brookfield asset management": "brookfield.com",
  "blackstone real estate": "blackstone.com",
  "boston properties": "bostonproperties.com",
  "vornado": "vno.com",
  "sl green": "slgreen.com",
  "mack-cali": "mack-cali.com",
  "ventas": "ventasreit.com",
  "welltower": "welltower.com",
  "healthpeak": "healthpeak.com",
  "american tower": "americantower.com",
  "crown castle": "crowncastle.com",
  "sbac communications": "sbasite.com",
  "unibail-rodamco-westfield": "urw.com",
  "unibail": "urw.com",
  "westfield": "westfield.com",
  "macerich": "macerich.com",
  "tanger outlets": "tangeroutlets.com",
  "federal realty": "federalrealty.com",
  "regency centers": "regencycenters.com",

  // ── Industrial & Manufacturing ─────────────────────────────────────────────
  "3m": "3m.com",
  "honeywell": "honeywell.com",
  "emerson electric": "emerson.com",
  "emerson": "emerson.com",
  "eaton": "eaton.com",
  "parker hannifin": "parker.com",
  "parker": "parker.com",
  "illinois tool works": "itw.com",
  "itw": "itw.com",
  "dover corporation": "dovercorporation.com",
  "dover": "dovercorporation.com",
  "roper technologies": "ropertech.com",
  "roper": "ropertech.com",
  "xylem": "xylem.com",
  "pentair": "pentair.com",
  "idex": "idexcorp.com",
  "ametek": "ametek.com",
  "moog": "moog.com",
  "woodward": "woodward.com",
  "curtiss-wright": "curtisswright.com",
  "heico": "heico.com",
  "transdigm": "transdigm.com",
  "spirit aerosystems": "spiritaero.com",
  "triumph group": "triumphgroup.com",
  "kaman": "kaman.com",
  "ge": "ge.com",
  "general electric": "ge.com",
  "ge aerospace": "geaerospace.com",
  "ge vernova": "gevernova.com",
  "ge healthcare": "gehealthcare.com",
  "siemens": "siemens.com",
  "siemens energy": "siemens-energy.com",
  "siemens healthineers": "siemens-healthineers.com",
  "abb": "abb.com",
  "schneider electric": "se.com",
  "legrand": "legrand.com",
  "rockwell automation": "rockwellautomation.com",
  "rockwell": "rockwellautomation.com",
  "keyence": "keyence.com",
  "fanuc": "fanuc.com",
  "yaskawa": "yaskawa.com",
  "kuka": "kuka.com",
  "universal robots": "universal-robots.com",
  "boston dynamics": "bostondynamics.com",
  "cognex": "cognex.com",
  "teradyne": "teradyne.com",
  "zebra technologies": "zebra.com",
  "zebra": "zebra.com",
  "datalogic": "datalogic.com",
  "honeywell safety": "honeywellsafety.com",
  "msa safety": "msasafety.com",
  "msa": "msasafety.com",
  "mine safety appliances": "msasafety.com",
  "alpha pro tech": "alphaprotech.com",
  "ansell": "ansell.com",
  "kimberly-clark": "kimberly-clark.com",
  "kimberly clark": "kimberly-clark.com",
  "procter & gamble": "pg.com",
  "p&g": "pg.com",
  "pg": "pg.com",
  "colgate-palmolive": "colgatepalmolive.com",
  "colgate palmolive": "colgatepalmolive.com",
  "colgate": "colgate.com",
  "church & dwight": "churchdwight.com",
  "clorox": "thecloroxcompany.com",
  "reckitt": "reckitt.com",
  "henkel": "henkel.com",
  "sc johnson": "scjohnson.com",
  "energizer": "energizer.com",
  "spectrum brands": "spectrumbrands.com",
  "edgewell": "edgewell.com",
  "prestige brands": "prestigebrandsinc.com",
  "prestige consumer healthcare": "prestigeconsumerhealthcare.com",
  "bhp": "bhp.com",
  "rio tinto": "riotinto.com",
  "vale": "vale.com",
  "glencore": "glencore.com",
  "anglo american": "angloamerican.com",
  "barrick gold": "barrick.com",
  "barrick": "barrick.com",
  "newmont": "newmont.com",
  "freeport-mcmoran": "fcx.com",
  "freeport mcmoran": "fcx.com",
  "nucor": "nucor.com",
  "steel dynamics": "steeldynamics.com",
  "arcelor mittal": "arcelormittal.com",
  "arcelormittal": "arcelormittal.com",
  "us steel": "ussteel.com",
  "cleveland-cliffs": "clevelandcliffs.com",
  "commercial metals": "cmc.com",
  "reliance steel": "rsac.com",
  "alcoa": "alcoa.com",
  "novelis": "novelis.com",
  "ball corporation": "ball.com",
  "crown holdings": "crowncork.com",
  "ardagh": "ardaghgroup.com",
  "silgan": "silgan.com",
  "sealed air": "sealedair.com",
  "packaging corp": "packagingcorp.com",
  "international paper": "internationalpaper.com",
  "ip": "internationalpaper.com",
  "georgia-pacific": "gapac.com",
  "georgia pacific": "gapac.com",
  "westrock": "westrock.com",
  "sonoco": "sonoco.com",
  "greif": "greif.com",
  "pactiv": "pactivevergreen.com",
  "berry global": "berryglobal.com",
  "avery dennison": "averydennison.com",

  // ── Construction & Engineering ────────────────────────────────────────────
  "bechtel": "bechtel.com",
  "fluor": "fluor.com",
  "aecom": "aecom.com",
  "jacobs engineering": "jacobs.com",
  "jacobs": "jacobs.com",
  "kbr": "kbr.com",
  "mcdermott": "mcdermott.com",
  "worley": "worley.com",
  "turner construction": "turnerconstruction.com",
  "skanska": "skanska.com",
  "mortenson": "mortenson.com",
  "hensel phelps": "henselphelps.com",
  "whiting-turner": "whiting-turner.com",
  "walsh group": "walshgroup.com",
  "clark construction": "clarkconstruction.com",
  "gilbane": "gilbaneco.com",
  "balfour beatty": "balfourbeatty.com",
  "vinci": "vinci.com",
  "bouygues": "bouygues.com",
  "hochtief": "hochtief.com",
  "strabag": "strabag.com",
  "ferrovial": "ferrovial.com",
  "acs group": "grupoacs.com",
  "lendlease": "lendlease.com",
  "john laing": "johnlaing.com",
  "mott macdonald": "mottmac.com",
  "wsatkins": "wsatkins.com",
  "atkins": "wsatkins.com",
  "wsp": "wsp.com",
  "arup": "arup.com",
  "halcrow": "halcrow.com",
  "gh": "ghd.com",
  "ghd": "ghd.com",
  "parsons": "parsons.com",

  // ── Education ─────────────────────────────────────────────────────────────
  "chegg": "chegg.com",
  "coursera": "coursera.org",
  "udemy": "udemy.com",
  "khan academy": "khanacademy.org",
  "edx": "edx.org",
  "udacity": "udacity.com",
  "2u": "2u.com",
  "duolingo": "duolingo.com",
  "rosetta stone": "rosettastone.com",
  "pearson": "pearson.com",
  "mcgraw-hill": "mheducation.com",
  "mcgraw hill": "mheducation.com",
  "cengage": "cengage.com",
  "john wiley": "wiley.com",
  "wiley": "wiley.com",
  "houghton mifflin": "hmco.com",
  "scholastic": "scholastic.com",
  "kaplan": "kaplan.com",
  "princeton review": "princetonreview.com",
  "testprep": "testprep.com",
  "collegeboard": "collegeboard.org",
  "college board": "collegeboard.org",
  "act": "act.org",
  "ets": "ets.org",
  "gmat": "mba.com",
  "gre": "ets.org",

  // ── Hospitality & Travel ──────────────────────────────────────────────────
  "marriott": "marriott.com",
  "marriott international": "marriott.com",
  "hilton": "hilton.com",
  "ihg": "ihg.com",
  "intercontinental hotels": "ihg.com",
  "hyatt": "hyatt.com",
  "wyndham": "wyndhamhotels.com",
  "choice hotels": "choicehotels.com",
  "best western": "bestwestern.com",
  "radisson": "radissonhotels.com",
  "accor": "accor.com",
  "shangri-la": "shangri-la.com",
  "shangri la": "shangri-la.com",
  "four seasons": "fourseasons.com",
  "rosewood": "rosewoodhotels.com",
  "peninsula hotels": "peninsula.com",
  "mandarin oriental": "mandarinoriental.com",
  "raffles": "raffles.com",
  "aman": "aman.com",
  "airbnb": "airbnb.com",
  "booking.com": "booking.com",
  "booking holdings": "bookingholdings.com",
  "expedia": "expedia.com",
  "expedia group": "expediagroup.com",
  "tripadvisor": "tripadvisor.com",
  "hotels.com": "hotels.com",
  "kayak": "kayak.com",
  "priceline": "priceline.com",
  "agoda": "agoda.com",
  "vrbo": "vrbo.com",
  "homeaway": "homeaway.com",
  "trivago": "trivago.com",
  "carnival corporation": "carnivalcorp.com",
  "carnival": "carnival.com",
  "royal caribbean": "royalcaribbean.com",
  "norwegian cruise line": "ncl.com",
  "ncl": "ncl.com",
  "msc cruises": "msccruises.com",
  "disney cruises": "disneycruise.disney.go.com",
  "celebrity cruises": "celebritycruises.com",

  // ── Diversified Conglomerates ──────────────────────────────────────────────
  "conglomerate berkshire": "berkshirehathaway.com",
  "ge conglomerate": "ge.com",
  "lg group": "lg.com",
  "samsung group": "samsung.com",
  "sk group": "sk.com",
  "sk": "sk.com",
  "hyundai group": "hyundai.com",
  "lotte": "lotte.co.kr",
  "hanwha": "hanwha.com",
  "posco": "posco.com",
  "tata group": "tata.com",
  "tata": "tata.com",
  "reliance industries": "ril.com",
  "reliance": "ril.com",
  "mahindra": "mahindra.com",
  "bajaj": "bajaj.com",
  "infra indiabulls": "indiabulls.com",
  "adani": "adani.com",
  "adani group": "adani.com",
  "softbank group": "softbank.jp",
  "sony group": "sony.com",
  "panasonic holdings": "panasonic.com",
  "mitsubishi corporation": "mitsubishi.com",
  "mitsui": "mitsui.com",
  "sumitomo": "sumitomocorp.com",
  "itochu": "itochu.co.jp",
  "marubeni": "marubeni.com",
  "toyota industries": "toyota-industries.com",
  "toyota tsusho": "toyota-tsusho.com",
  "daewoo": "daewoo.com",
  "hutchison": "hutchison.com.hk",
  "citic": "citic.com",
  "jardine matheson": "jardines.com",
  "swire": "swire.com",
  "hutchison whampoa": "hutchison.com.hk",
  "li & fung": "lifung.com",
  "taipan": "taipan.com",
  "siemens ag": "siemens.com",
  "thyssenkrupp": "thyssenkrupp.com",
  "rheinmetall": "rheinmetall.com",
  "continental ag": "continental.com",
  "bosch": "bosch.com",
  "robert bosch": "bosch.com",
  "daimler truck": "daimler-truck.com",
  "traton": "traton.com",
  "man trucks": "man.eu",
  "volvo group": "volvogroup.com",
  "scania": "scania.com",
  "iveco": "iveco.com",
  "paccar": "paccar.com",
  "kenworth": "kenworth.com",
  "peterbilt": "peterbilt.com",
  "freightliner": "freightliner.com",
  "navistar": "navistar.com",

  // ── Agriculture ───────────────────────────────────────────────────────────
  "corteva": "corteva.com",
  "syngenta": "syngenta.com",
  "bayer crop science": "bayer.com",
  "dow agrosciences": "dow.com",
  "fmc corporation": "fmc.com",
  "fmc": "fmc.com",
  "land o'lakes": "landolakes.com",
  "land o lakes": "landolakes.com",
  "dairy farmers of america": "dfamilk.com",
  "dfa": "dfamilk.com",
  "agco": "agcocorp.com",
  "case ih": "caseih.com",
  "new holland": "newholland.com",
  "claas": "claas.com",
  "kuhn": "kuhn.com",
  "trimble": "trimble.com",

  // ── Staffing & HR ─────────────────────────────────────────────────────────
  "workday hr": "workday.com",
  "adp": "adp.com",
  "automatic data processing": "adp.com",
  "paychex": "paychex.com",
  "ceridian": "ceridian.com",
  "dayforce": "dayforce.com",
  "bamboohr": "bamboohr.com",
  "greenhouse": "greenhouse.io",
  "lever": "lever.co",
  "icims": "icims.com",
  "taleo": "oracle.com",
  "successfactors": "successfactors.com",
  "sap successfactors": "sap.com",
  "lattice": "lattice.com",
  "rippling": "rippling.com",
  "gusto": "gusto.com",
  "justworks": "justworks.com",
  "namely": "namely.com",
  "personio": "personio.com",
  "hibob": "hibob.com",
  "factorial": "factorialhr.com",
  "remote": "remote.com",
  "deel": "deel.com",
  "papaya global": "papayaglobal.com",
  "globalisation partners": "globalization-partners.com",

  // ── Legal ─────────────────────────────────────────────────────────────────
  "kirkland & ellis": "kirkland.com",
  "latham & watkins": "lw.com",
  "skadden arps": "skadden.com",
  "skadden": "skadden.com",
  "sullivan & cromwell": "sullcrom.com",
  "cravath": "cravath.com",
  "paul weiss": "paulweiss.com",
  "weil gotshal": "weil.com",
  "white & case": "whitecase.com",
  "cleary gottlieb": "clearygottlieb.com",
  "simpson thacher": "stblaw.com",
  "debevoise & plimpton": "debevoise.com",
  "jones day": "jonesday.com",
  "baker mckenzie": "bakermckenzie.com",
  "dentons": "dentons.com",
  "norton rose fulbright": "nortonrosefulbright.com",
  "clifford chance": "cliffordchance.com",
  "freshfields": "freshfields.com",
  "linklaters": "linklaters.com",
  "allen & overy": "allenovery.com",
  "hogan lovells": "hoganlovells.com",
  "dla piper": "dlapiper.com",
  "mayer brown": "mayerbrown.com",
  "reed smith": "reedsmith.com",
  "greenberg traurig": "gtlaw.com",
  "morgan lewis": "morganlewis.com",
  "pillsbury": "pillsburylaw.com",
  "wilmer hale": "wilmerhale.com",
  "covington burling": "cov.com",
  "orrick": "orrick.com",
  "fenwick": "fenwick.com",
  "cooley": "cooley.com",
  "wilson sonsini": "wsgr.com",
  "gunderson dettmer": "gunder.com",
  "goodwin procter": "goodwinlaw.com",

  // ── Additional notable companies ──────────────────────────────────────────
  "twitter x": "x.com",
  "spacex starlink": "starlink.com",
  "starlink": "starlink.com",
  "palantir technologies": "palantir.com",
  "anduril": "anduril.com",
  "shield ai": "shield.ai",
  "primer ai": "primer.ai",
  "samsara": "samsara.com",
  "lytx": "lytx.com",
  "mobileye": "mobileye.com",
  "waymo": "waymo.com",
  "cruise": "getcruise.com",
  "aurora": "aurora.tech",
  "zoox": "zoox.com",
  "nuro": "nuro.ai",
  "argo ai": "argo.ai",
  "argo": "argo.ai",
  "motional": "motional.com",
  "comma ai": "comma.ai",
  "woven planet": "woven.toyota",
  "peloton": "onepeloton.com",
  "mirror": "mirror.co",
  "whoop": "whoop.com",
  "oura": "ouraring.com",
  "fitbit": "fitbit.com",
  "garmin": "garmin.com",
  "polar": "polar.com",
  "suunto": "suunto.com",
  "wahoo": "wahoofitness.com",
  "noom": "noom.com",
  "weight watchers": "weightwatchers.com",
  "ww": "ww.com",
  "hims & hers": "forhims.com",
  "ro": "ro.co",
  "sesame care": "sesamecare.com",
  "forward": "goforward.com",
  "one medical": "onemedical.com",
  "heal": "heal.com",
  "teladoc": "teladoc.com",
  "mdlive": "mdlive.com",
  "amwell": "amwell.com",
  "doxy.me": "doxy.me",
  "hippo insurance": "hippo.com",
  "lemonade": "lemonade.com",
  "root insurance": "joinroot.com",
  "root": "joinroot.com",
  "oscar health": "hioscar.com",
  "oscar": "hioscar.com",
  "devoted health": "devoted.com",
  "alignment health": "alignmenthealth.com",
  "clover health": "cloverhealth.com",
  "cityblock": "cityblock.com",
  "iora health": "iorahealth.com",
  "carbon health": "carbonhealth.com",
  "cerebral": "getcerebral.com",
  "calm": "calm.com",
  "headspace": "headspace.com",
  "talkspace": "talkspace.com",
  "betterhelp": "betterhelp.com",

  // ── Miscellaneous well-known brands ───────────────────────────────────────
  "xerox": "xerox.com",
  "pitney bowes": "pitneybowes.com",
  "iron mountain storage": "ironmountain.com",
  "ricoh": "ricoh.com",
  "brother": "brother.com",
  "lexmark": "lexmark.com",
  "canon": "canon.com",
  "epson": "epson.com",
  "seagate": "seagate.com",
  "western digital": "westerndigital.com",
  "wd": "westerndigital.com",
  "kingston": "kingston.com",
  "sandisk": "sandisk.com",
  "micron": "micron.com",
  "sk hynix": "skhynix.com",
  "hynix": "skhynix.com",
  "kioxia": "kioxia.com",
  "nxp semiconductors": "nxp.com",
  "nxp": "nxp.com",
  "infineon": "infineon.com",
  "st microelectronics": "st.com",
  "stmicroelectronics": "st.com",
  "microchip technology": "microchip.com",
  "renesas": "renesas.com",
  "on semiconductor": "onsemi.com",
  "onsemi": "onsemi.com",
  "lattice semiconductor": "latticesemi.com",
  "xilinx": "xilinx.com",
  "altera": "altera.com",
  "arm": "arm.com",
  "arm holdings": "arm.com",
  "risc-v": "riscv.org",
  "synopsys": "synopsys.com",
  "cadence": "cadence.com",
  "mentor graphics": "mentor.com",
  "ansys": "ansys.com",
  "altair": "altair.com",
  "siemens eda": "siemens.com",
  "zuken": "zuken.com",
  "aveva": "aveva.com",
  "ptc": "ptc.com",
  "dassault systemes": "3ds.com",
  "3ds": "3ds.com",
  "autodesk": "autodesk.com",
  "bentley systems": "bentley.com",
  "trimble navigation": "trimble.com",
  "hexagon": "hexagon.com",
  "faro technologies": "faro.com",
  "leica geosystems": "leica-geosystems.com",
  "trimble agriculture": "trimble.com",
  "esri": "esri.com",
  "mapbox": "mapbox.com",
  "here": "here.com",
  "tomtom": "tomtom.com",
  "garmin aviation": "garmin.com",
  "jeppesen": "jeppesen.com",
  "fltplan": "fltplan.com",
};
