/**
 * Company and role metadata for role detail page. Based on LiveDataTechnologies workforce context.
 */

export interface CompanyInfo {
  description: string;
  industry: string;
  employeeCount: string;
}

/** Detailed, professional company descriptions for the role detail page. */
export const COMPANY_INFO: Record<string, CompanyInfo> = {
  Stripe: { description: "Stripe provides financial infrastructure for the internet, enabling businesses of all sizes to accept payments, manage revenue, and run their operations globally. The company is recognized for its developer-first approach, robust APIs, and commitment to expanding economic access. Stripe serves millions of companies across more than 46 countries.", industry: "Technology / Fintech", employeeCount: "8,000+" },
  Google: { description: "Google’s mission is to organize the world’s information and make it universally accessible and useful. The company operates across search, advertising, cloud computing (Google Cloud), software and hardware (Android, Chrome, Pixel), and content (YouTube). Google is a subsidiary of Alphabet Inc. and maintains a significant presence in research and development.", industry: "Technology", employeeCount: "190,000+" },
  Meta: { description: "Meta builds technologies that help people connect, find communities, and grow businesses. Its family of apps includes Facebook, Instagram, WhatsApp, and Messenger, and it invests in immersive experiences through Reality Labs. Meta operates at scale globally and focuses on responsible innovation and long-term research.", industry: "Technology", employeeCount: "87,000+" },
  Microsoft: { description: "Microsoft is a leading technology company that develops and supports software, devices, and services. Its portfolio includes the Microsoft Cloud (Azure), Microsoft 365, Windows, LinkedIn, and gaming (Xbox). The company serves consumers, enterprises, and the public sector with a focus on empowering every person and organization to achieve more.", industry: "Technology", employeeCount: "220,000+" },
  Apple: { description: "Apple designs, manufactures, and markets consumer electronics, software, and services worldwide. Its product lines include iPhone, Mac, iPad, Apple Watch, and Apple TV, alongside services such as the App Store, Apple Music, and iCloud. Apple is known for its integration of hardware, software, and services and its emphasis on privacy and accessibility.", industry: "Technology", employeeCount: "164,000+" },
  Amazon: { description: "Amazon is a diversified technology and commerce company with operations in e-commerce, digital streaming, cloud computing (Amazon Web Services), logistics, and devices. It is one of the world’s largest employers and invests heavily in innovation, sustainability, and customer experience across consumer and enterprise segments.", industry: "Technology", employeeCount: "1,500,000+" },
  Netflix: { description: "Netflix is a leading subscription-based streaming service that offers films, series, and documentaries across numerous languages and genres. The company produces and licenses content for audiences worldwide and is known for data-driven content strategy and a culture that emphasizes freedom and responsibility.", industry: "Technology / Media", employeeCount: "13,000+" },
  Notion: { description: "Notion provides an all-in-one workspace where teams can write, plan, collaborate, and manage projects. The product combines notes, docs, wikis, and project management in a flexible, customizable platform. Notion is used by organizations of all sizes for knowledge management and workflow coordination.", industry: "Technology", employeeCount: "500+" },
  Vercel: { description: "Vercel is the platform for frontend developers, providing the infrastructure and tooling to build, scale, and secure web applications. The company is the creator of Next.js and is optimized for serverless deployment, edge functions, and modern frontend workflows. Enterprises and indie developers use Vercel for production deployments.", industry: "Technology", employeeCount: "500+" },
  Figma: { description: "Figma is a collaborative interface design platform used for UI and UX design, prototyping, and design systems. Teams use Figma to design in the browser with real-time collaboration, developer handoff, and integrated workflows. The company supports design at scale for product and design organizations.", industry: "Technology", employeeCount: "1,000+" },
  OpenAI: { description: "OpenAI is an AI research and deployment company whose mission is to ensure that artificial general intelligence benefits all of humanity. The company is known for ChatGPT and frontier language models, as well as APIs and products used by developers and enterprises. OpenAI works on safety, alignment, and broad access to AI capabilities.", industry: "Technology / AI", employeeCount: "500+" },
  Anthropic: { description: "Anthropic is an AI safety and research company focused on building reliable, interpretable, and steerable AI systems. The company develops general-purpose AI assistants and frontier models with a strong emphasis on safety research and responsible deployment. Anthropic works with enterprises and researchers to advance safe AI.", industry: "Technology / AI", employeeCount: "300+" },
  Salesforce: { description: "Salesforce is the global leader in customer relationship management (CRM), bringing companies and customers together. Its Customer 360 platform provides sales, service, marketing, commerce, and analytics solutions on a single integrated platform. Salesforce serves organizations across industries with cloud-based enterprise applications.", industry: "Technology", employeeCount: "70,000+" },
  HubSpot: { description: "HubSpot offers a connected platform for inbound marketing, sales, customer service, and CRM. The company provides software and resources that help businesses attract visitors, convert leads, and delight customers. HubSpot is known for its inbound methodology and scalable products for growing companies.", industry: "Technology", employeeCount: "7,000+" },
  Airbnb: { description: "Airbnb is a global marketplace that connects hosts who offer unique stays and experiences with guests seeking accommodations and activities. The platform supports millions of listings in nearly every country and emphasizes community, belonging, and sustainable travel. Airbnb operates in the travel and hospitality technology sector.", industry: "Technology", employeeCount: "6,000+" },
  Slack: { description: "Slack is a business communication platform that brings together people, applications, and information through channels, messaging, and integrations. Teams use Slack for real-time collaboration, workflow automation, and connectivity with other tools. Slack is part of the Salesforce ecosystem and is widely adopted by organizations of all sizes.", industry: "Technology", employeeCount: "2,000+" },
  Adobe: { description: "Adobe is a global software company known for creative, document, and digital experience solutions. Its products include Creative Cloud (Photoshop, Illustrator, and others), Document Cloud (Acrobat), and Experience Cloud for marketing and analytics. Adobe serves creative professionals, enterprises, and consumers worldwide.", industry: "Technology", employeeCount: "29,000+" },
  Spotify: { description: "Spotify is a leading audio streaming and media services provider, offering millions of tracks and podcasts to listeners and creators globally. The company operates a two-sided platform for consumers and artists, with both ad-supported and subscription tiers. Spotify invests in discovery, personalization, and audio innovation.", industry: "Technology / Media", employeeCount: "9,000+" },
  GitHub: { description: "GitHub is the world’s leading software development and collaboration platform, providing version control, CI/CD, code review, and project management. Millions of developers and organizations host and manage code on GitHub. The platform is central to open source and enterprise software development.", industry: "Technology", employeeCount: "3,000+" },
  MongoDB: { description: "MongoDB is a general-purpose document database platform designed for modern application development. The company’s database and data services enable developers to build and run applications at scale with flexibility and performance. MongoDB serves startups, enterprises, and government agencies across industries.", industry: "Technology", employeeCount: "5,000+" },
  Nvidia: { description: "Nvidia is a pioneer in GPU computing and AI. The company’s platforms power graphics, data center, professional visualization, and autonomous vehicle applications. Nvidia is a leading provider of accelerators and software for AI training and inference and is central to the expansion of accelerated computing.", industry: "Technology", employeeCount: "29,000+" },
  Uber: { description: "Uber is a mobility and delivery platform that connects riders with drivers and customers with restaurants and merchants. The company operates ride-sharing and Uber Eats in numerous countries and invests in autonomous vehicles and new mobility solutions. Uber focuses on safety, reliability, and expanding access to transportation and delivery.", industry: "Technology", employeeCount: "32,000+" },
  Lyft: { description: "Lyft is a rideshare and mobility company that provides transportation options across North America. The company connects drivers and riders through its app and has expanded into shared rides, bikes, and scooters. Lyft emphasizes community, sustainability, and improving urban mobility.", industry: "Technology", employeeCount: "4,000+" },
  DoorDash: { description: "DoorDash is a local logistics platform that connects consumers with restaurants, grocers, and retail partners for on-demand delivery. The company operates one of the largest last-mile logistics networks in the United States and internationally. DoorDash supports merchants, dashers, and consumers through technology and operations.", industry: "Technology", employeeCount: "20,000+" },
  Coinbase: { description: "Coinbase is a cryptocurrency exchange and infrastructure provider that enables users and institutions to buy, sell, and store digital assets. The company offers products for retail and institutional clients and is focused on regulatory compliance and building the cryptoeconomy. Coinbase operates in multiple jurisdictions worldwide.", industry: "Technology / Fintech", employeeCount: "3,000+" },
  Square: { description: "Square provides financial services and mobile payment solutions for businesses. The company offers point-of-sale systems, banking (Square Banking), and software for payments, payroll, and commerce. Square serves sellers, individuals, and developers with an integrated ecosystem of tools and APIs.", industry: "Technology / Fintech", employeeCount: "8,000+" },
  Zoom: { description: "Zoom is a leading video communications platform that provides meetings, chat, phone, webinars, and virtual events for businesses and individuals. The company is known for reliable, easy-to-use video collaboration and has become essential for remote and hybrid work. Zoom serves organizations globally across industries.", industry: "Technology", employeeCount: "7,000+" },
  Okta: { description: "Okta is the identity company that provides secure access and identity management for people and applications. The company’s platform enables single sign-on, multi-factor authentication, lifecycle management, and API access management. Okta helps organizations secure their workforce and customer identity at scale.", industry: "Technology", employeeCount: "6,000+" },
  ServiceNow: { description: "ServiceNow delivers enterprise workflow and IT service management through a single cloud platform. The company’s products digitize and automate workflows for IT, employee and customer service, security, and industry-specific processes. ServiceNow serves large enterprises and public sector organizations worldwide.", industry: "Technology", employeeCount: "22,000+" },
  IBM: { description: "IBM is a global technology and consulting company that provides hybrid cloud, AI, and enterprise software and services. The company helps clients modernize infrastructure, automate operations, and integrate data and AI into their workflows. IBM has a long history of research and innovation and serves industries worldwide.", industry: "Technology", employeeCount: "280,000+" },
  Oracle: { description: "Oracle offers integrated suites of enterprise software, cloud applications, and database and cloud infrastructure. The company’s products span ERP, database, cloud computing, and industry solutions. Oracle serves enterprises and governments with a focus on performance, security, and scalability.", industry: "Technology", employeeCount: "140,000+" },
  Cisco: { description: "Cisco is a global leader in networking, security, and collaboration technologies. The company provides hardware and software for IT infrastructure, including data center, cloud, and hybrid work. Cisco serves enterprises, service providers, and public sector organizations with a broad portfolio of solutions.", industry: "Technology", employeeCount: "80,000+" },
  Linear: { description: "Linear is a modern issue tracking and project management tool built for software teams. The company focuses on speed, clarity, and minimal friction in planning and shipping software. Linear is used by product and engineering teams who value a focused, keyboard-first workflow.", industry: "Technology", employeeCount: "100+" },
  Dropbox: { description: "Dropbox is a cloud storage and collaboration company that helps people and teams sync, backup, and share files. The company offers file storage, document collaboration, and workflow integrations for individuals and businesses. Dropbox emphasizes simplicity and reliability across devices and platforms.", industry: "Technology", employeeCount: "2,000+" },
  Atlassian: { description: "Atlassian provides team collaboration and productivity software used by development and business teams globally. Its products include Jira, Confluence, Trello, and Bitbucket for project management, documentation, and code collaboration. Atlassian supports agile practices and scale for organizations of all sizes.", industry: "Technology", employeeCount: "11,000+" },
  Twilio: { description: "Twilio provides a customer engagement platform and communications APIs that enable developers and businesses to build messaging, voice, and video into applications. The company’s platform supports programmable communications and contact center solutions. Twilio serves startups and enterprises across industries.", industry: "Technology", employeeCount: "5,000+" },
  Snowflake: { description: "Snowflake is a cloud data platform that enables data warehousing, data lakes, and data sharing. The company’s architecture separates compute and storage and runs on major public clouds. Snowflake is used by organizations for analytics, data engineering, and secure data collaboration.", industry: "Technology", employeeCount: "7,000+" },
  Databricks: { description: "Databricks provides a unified data and AI platform built on a lakehouse architecture. The company combines data warehousing and data lakes with machine learning and analytics. Databricks is used for ETL, ML workflows, and business intelligence by data and engineering teams globally.", industry: "Technology", employeeCount: "6,000+" },
  Elastic: { description: "Elastic is the company behind the Elastic Stack (Elasticsearch, Kibana, Beats, Logstash), used for search, observability, and security. The company’s products power application search, logging, metrics, and security analytics. Elastic serves developers and enterprises with open source and managed offerings.", industry: "Technology", employeeCount: "3,000+" },
  HashiCorp: { description: "HashiCorp provides infrastructure automation software used for provisioning, security, and runtime. Its products include Terraform, Vault, Consul, and Nomad for multi-cloud infrastructure. HashiCorp serves DevOps and platform teams in enterprises and cloud-native organizations.", industry: "Technology", employeeCount: "2,000+" },
  GitLab: { description: "GitLab is a complete DevOps lifecycle platform delivered as a single application. The company provides source code management, CI/CD, security, and planning in one place. GitLab is used by development teams for collaboration and automation from planning to monitoring.", industry: "Technology", employeeCount: "2,000+" },
  Twitch: { description: "Twitch is a live streaming platform where creators and communities gather around gaming, music, and other content. The company is a subsidiary of Amazon and supports millions of streamers and viewers. Twitch focuses on interactive entertainment and creator monetization.", industry: "Technology / Media", employeeCount: "2,000+" },
  DocuSign: { description: "DocuSign provides electronic signature and agreement cloud solutions for digital transaction management. The company’s platform enables organizations to prepare, sign, and manage agreements electronically. DocuSign serves enterprises and SMBs across industries for contract lifecycle management.", industry: "Technology", employeeCount: "7,000+" },
  Workday: { description: "Workday provides enterprise cloud applications for finance and human resources. The company’s platform supports financial management, planning, HR, payroll, and analytics. Workday is used by large organizations for unified data and processes across finance and people operations.", industry: "Technology", employeeCount: "18,000+" },
};

const HIGH_DEMAND_COMPANIES = new Set(["Google", "Meta", "Microsoft", "Apple", "Amazon", "Netflix", "Stripe", "OpenAI", "Anthropic", "Nvidia"]);

export type DifficultyLevel = "Easier" | "Moderate" | "Competitive" | "Very competitive";

/**
 * Difficulty to get the job based on LiveDataTechnologies workforce data:
 * level (intern/entry vs senior/director) and company demand.
 */
export function getDifficulty(company: string, level: string): { level: DifficultyLevel; note: string } {
  const lev = (level || "entry").toLowerCase();
  const isTopTier = HIGH_DEMAND_COMPANIES.has(company);
  const isSeniorOrAbove = ["senior", "manager", "director", "vp", "c_suite"].includes(lev);

  if (lev === "intern" && !isTopTier) {
    return { level: "Easier", note: "Intern roles typically have more openings relative to applicants in this segment (LiveDataTechnologies workforce data)." };
  }
  if (lev === "intern" && isTopTier) {
    return { level: "Moderate", note: "Competitive intern programs; strong alignment with your pathway improves odds (LiveDataTechnologies)." };
  }
  if (lev === "entry" && !isTopTier) {
    return { level: "Moderate", note: "Entry-level roles show steady hiring in this function (LiveDataTechnologies workforce patterns)." };
  }
  if (lev === "entry" && isTopTier) {
    return { level: "Competitive", note: "High applicant volume at this company; relevant experience and fit matter (LiveDataTechnologies)." };
  }
  if (isSeniorOrAbove && isTopTier) {
    return { level: "Very competitive", note: "Senior roles at top companies are highly selective. Workforce data shows fewer openings and strong competition." };
  }
  if (isSeniorOrAbove) {
    return { level: "Competitive", note: "Senior positions typically require demonstrated experience; workforce data reflects selective hiring." };
  }
  return { level: "Moderate", note: "Hiring demand varies by function and location (LiveDataTechnologies)." };
}
