/**
 * US Universities list for autocomplete + domain-to-logo lookups.
 * Domain is used to attempt a Clearbit logo fetch.
 */
export interface UniversityRecord {
  name: string;
  /** Clearbit-fetchable domain, e.g. "stanford.edu" */
  domain: string;
}

export const US_UNIVERSITIES: UniversityRecord[] = [
  // ── Ivy League ─────────────────────────────────────────────────────────────
  { name: "Harvard University", domain: "harvard.edu" },
  { name: "Yale University", domain: "yale.edu" },
  { name: "Princeton University", domain: "princeton.edu" },
  { name: "Columbia University", domain: "columbia.edu" },
  { name: "University of Pennsylvania", domain: "upenn.edu" },
  { name: "Brown University", domain: "brown.edu" },
  { name: "Dartmouth College", domain: "dartmouth.edu" },
  { name: "Cornell University", domain: "cornell.edu" },
  // ── Top Private Universities ───────────────────────────────────────────────
  { name: "Massachusetts Institute of Technology", domain: "mit.edu" },
  { name: "Stanford University", domain: "stanford.edu" },
  { name: "California Institute of Technology", domain: "caltech.edu" },
  { name: "Duke University", domain: "duke.edu" },
  { name: "Northwestern University", domain: "northwestern.edu" },
  { name: "Johns Hopkins University", domain: "jhu.edu" },
  { name: "Vanderbilt University", domain: "vanderbilt.edu" },
  { name: "Rice University", domain: "rice.edu" },
  { name: "Washington University in St. Louis", domain: "wustl.edu" },
  { name: "Emory University", domain: "emory.edu" },
  { name: "Notre Dame University", domain: "nd.edu" },
  { name: "Georgetown University", domain: "georgetown.edu" },
  { name: "Carnegie Mellon University", domain: "cmu.edu" },
  { name: "University of Southern California", domain: "usc.edu" },
  { name: "Tufts University", domain: "tufts.edu" },
  { name: "Boston College", domain: "bc.edu" },
  { name: "Boston University", domain: "bu.edu" },
  { name: "Northeastern University", domain: "northeastern.edu" },
  { name: "Tulane University", domain: "tulane.edu" },
  { name: "Case Western Reserve University", domain: "case.edu" },
  { name: "Lehigh University", domain: "lehigh.edu" },
  { name: "Fordham University", domain: "fordham.edu" },
  { name: "George Washington University", domain: "gwu.edu" },
  { name: "American University", domain: "american.edu" },
  { name: "New York University", domain: "nyu.edu" },
  { name: "Syracuse University", domain: "syr.edu" },
  { name: "Drexel University", domain: "drexel.edu" },
  { name: "Temple University", domain: "temple.edu" },
  { name: "Villanova University", domain: "villanova.edu" },
  { name: "Marquette University", domain: "marquette.edu" },
  { name: "Santa Clara University", domain: "scu.edu" },
  { name: "Gonzaga University", domain: "gonzaga.edu" },
  { name: "Wake Forest University", domain: "wfu.edu" },
  { name: "University of Richmond", domain: "richmond.edu" },
  { name: "Trinity University", domain: "trinity.edu" },
  { name: "Colgate University", domain: "colgate.edu" },
  { name: "Hamilton College", domain: "hamilton.edu" },
  { name: "Bowdoin College", domain: "bowdoin.edu" },
  { name: "Middlebury College", domain: "middlebury.edu" },
  { name: "Amherst College", domain: "amherst.edu" },
  { name: "Williams College", domain: "williams.edu" },
  { name: "Swarthmore College", domain: "swarthmore.edu" },
  { name: "Haverford College", domain: "haverford.edu" },
  { name: "Pomona College", domain: "pomona.edu" },
  { name: "Claremont McKenna College", domain: "cmc.edu" },
  { name: "Harvey Mudd College", domain: "hmc.edu" },
  { name: "Wellesley College", domain: "wellesley.edu" },
  { name: "Smith College", domain: "smith.edu" },
  { name: "Mount Holyoke College", domain: "mtholyoke.edu" },
  { name: "Vassar College", domain: "vassar.edu" },
  { name: "Barnard College", domain: "barnard.edu" },
  { name: "Bryn Mawr College", domain: "brynmawr.edu" },
  { name: "Oberlin College", domain: "oberlin.edu" },
  { name: "Grinnell College", domain: "grinnell.edu" },
  { name: "Carleton College", domain: "carleton.edu" },
  { name: "Reed College", domain: "reed.edu" },
  { name: "Kenyon College", domain: "kenyon.edu" },
  { name: "Colorado College", domain: "coloradocollege.edu" },
  { name: "Macalester College", domain: "macalester.edu" },
  { name: "Bates College", domain: "bates.edu" },
  { name: "Colby College", domain: "colby.edu" },
  // ── Public Flagships ───────────────────────────────────────────────────────
  { name: "University of California Berkeley", domain: "berkeley.edu" },
  { name: "University of California Los Angeles", domain: "ucla.edu" },
  { name: "University of California San Diego", domain: "ucsd.edu" },
  { name: "University of California Davis", domain: "ucdavis.edu" },
  { name: "University of California Santa Barbara", domain: "ucsb.edu" },
  { name: "University of California Irvine", domain: "uci.edu" },
  { name: "University of California Santa Cruz", domain: "ucsc.edu" },
  { name: "University of California Riverside", domain: "ucr.edu" },
  { name: "University of Michigan", domain: "umich.edu" },
  { name: "University of Virginia", domain: "virginia.edu" },
  { name: "University of North Carolina at Chapel Hill", domain: "unc.edu" },
  { name: "University of Texas at Austin", domain: "utexas.edu" },
  { name: "Georgia Institute of Technology", domain: "gatech.edu" },
  { name: "University of Florida", domain: "ufl.edu" },
  { name: "University of Wisconsin Madison", domain: "wisc.edu" },
  { name: "University of Illinois Urbana-Champaign", domain: "illinois.edu" },
  { name: "Penn State University", domain: "psu.edu" },
  { name: "Ohio State University", domain: "osu.edu" },
  { name: "Purdue University", domain: "purdue.edu" },
  { name: "University of Minnesota", domain: "umn.edu" },
  { name: "University of Washington", domain: "uw.edu" },
  { name: "University of Maryland", domain: "umd.edu" },
  { name: "University of Georgia", domain: "uga.edu" },
  { name: "University of Colorado Boulder", domain: "colorado.edu" },
  { name: "University of Arizona", domain: "arizona.edu" },
  { name: "Arizona State University", domain: "asu.edu" },
  { name: "University of Utah", domain: "utah.edu" },
  { name: "Utah State University", domain: "usu.edu" },
  { name: "Colorado State University", domain: "colostate.edu" },
  { name: "University of Oregon", domain: "uoregon.edu" },
  { name: "Oregon State University", domain: "oregonstate.edu" },
  { name: "Washington State University", domain: "wsu.edu" },
  { name: "University of Nevada Las Vegas", domain: "unlv.edu" },
  { name: "University of Nevada Reno", domain: "unr.edu" },
  { name: "Boise State University", domain: "boisestate.edu" },
  { name: "University of Idaho", domain: "uidaho.edu" },
  { name: "University of Montana", domain: "umt.edu" },
  { name: "Montana State University", domain: "montana.edu" },
  { name: "University of Wyoming", domain: "uwyo.edu" },
  { name: "University of New Mexico", domain: "unm.edu" },
  { name: "New Mexico State University", domain: "nmsu.edu" },
  { name: "University of Oklahoma", domain: "ou.edu" },
  { name: "Oklahoma State University", domain: "okstate.edu" },
  { name: "Kansas State University", domain: "ksu.edu" },
  { name: "University of Kansas", domain: "ku.edu" },
  { name: "University of Nebraska Lincoln", domain: "unl.edu" },
  { name: "Iowa State University", domain: "iastate.edu" },
  { name: "University of Iowa", domain: "uiowa.edu" },
  { name: "University of Missouri", domain: "missouri.edu" },
  { name: "Missouri University of Science and Technology", domain: "mst.edu" },
  { name: "University of Arkansas", domain: "uark.edu" },
  { name: "Louisiana State University", domain: "lsu.edu" },
  { name: "University of Mississippi", domain: "olemiss.edu" },
  { name: "Mississippi State University", domain: "msstate.edu" },
  { name: "University of Alabama", domain: "ua.edu" },
  { name: "Auburn University", domain: "auburn.edu" },
  { name: "University of Tennessee", domain: "utk.edu" },
  { name: "Tennessee Technological University", domain: "tntech.edu" },
  { name: "University of Kentucky", domain: "uky.edu" },
  { name: "University of Louisville", domain: "louisville.edu" },
  { name: "West Virginia University", domain: "wvu.edu" },
  { name: "Virginia Tech", domain: "vt.edu" },
  { name: "University of South Carolina", domain: "sc.edu" },
  { name: "Clemson University", domain: "clemson.edu" },
  { name: "Florida State University", domain: "fsu.edu" },
  { name: "University of Central Florida", domain: "ucf.edu" },
  { name: "University of South Florida", domain: "usf.edu" },
  { name: "Florida International University", domain: "fiu.edu" },
  { name: "Indiana University Bloomington", domain: "iu.edu" },
  { name: "Indiana University Purdue University Indianapolis", domain: "iupui.edu" },
  { name: "University of Notre Dame", domain: "nd.edu" },
  { name: "Michigan State University", domain: "msu.edu" },
  { name: "Wayne State University", domain: "wayne.edu" },
  { name: "University of Cincinnati", domain: "uc.edu" },
  { name: "University of Dayton", domain: "udayton.edu" },
  { name: "Miami University", domain: "miamioh.edu" },
  { name: "University of Pittsburgh", domain: "pitt.edu" },
  { name: "Rutgers University", domain: "rutgers.edu" },
  { name: "University of Connecticut", domain: "uconn.edu" },
  { name: "University of Rhode Island", domain: "uri.edu" },
  { name: "University of Vermont", domain: "uvm.edu" },
  { name: "University of New Hampshire", domain: "unh.edu" },
  { name: "University of Maine", domain: "umaine.edu" },
  { name: "University of Massachusetts Amherst", domain: "umass.edu" },
  { name: "University of Massachusetts Boston", domain: "umb.edu" },
  { name: "SUNY Buffalo", domain: "buffalo.edu" },
  { name: "SUNY Stony Brook", domain: "stonybrook.edu" },
  { name: "SUNY Binghamton", domain: "binghamton.edu" },
  { name: "SUNY Albany", domain: "albany.edu" },
  { name: "City University of New York", domain: "cuny.edu" },
  { name: "University of Delaware", domain: "udel.edu" },
  { name: "University of Hawaii at Manoa", domain: "hawaii.edu" },
  { name: "University of Alaska Fairbanks", domain: "uaf.edu" },
  // ── STEM / Technical Schools ───────────────────────────────────────────────
  { name: "Rensselaer Polytechnic Institute", domain: "rpi.edu" },
  { name: "Worcester Polytechnic Institute", domain: "wpi.edu" },
  { name: "Stevens Institute of Technology", domain: "stevens.edu" },
  { name: "Illinois Institute of Technology", domain: "iit.edu" },
  { name: "Rochester Institute of Technology", domain: "rit.edu" },
  { name: "New Jersey Institute of Technology", domain: "njit.edu" },
  { name: "University of Texas at Dallas", domain: "utdallas.edu" },
  { name: "Georgia State University", domain: "gsu.edu" },
  { name: "San Jose State University", domain: "sjsu.edu" },
  // ── HBCUs ──────────────────────────────────────────────────────────────────
  { name: "Howard University", domain: "howard.edu" },
  { name: "Morehouse College", domain: "morehouse.edu" },
  { name: "Spelman College", domain: "spelman.edu" },
  { name: "Hampton University", domain: "hamptonu.edu" },
  { name: "Tuskegee University", domain: "tuskegee.edu" },
  { name: "Florida A&M University", domain: "famu.edu" },
  { name: "North Carolina A&T State University", domain: "ncat.edu" },
  { name: "Historically Black College - Other", domain: "" },
  // ── Business / Law / Medical Schools ──────────────────────────────────────
  { name: "Babson College", domain: "babson.edu" },
  { name: "Bentley University", domain: "bentley.edu" },
  { name: "Bryant University", domain: "bryant.edu" },
  // ── Community Colleges / Other ─────────────────────────────────────────────
  { name: "Santa Monica College", domain: "smc.edu" },
  { name: "De Anza College", domain: "deanza.edu" },
  { name: "Pasadena City College", domain: "pasadena.edu" },
  { name: "El Camino College", domain: "elcamino.edu" },
  { name: "Foothill College", domain: "foothill.edu" },
  { name: "Miami Dade College", domain: "mdc.edu" },
  { name: "Houston Community College", domain: "hccs.edu" },
  { name: "Lone Star College", domain: "lonestar.edu" },
  { name: "Austin Community College", domain: "austincc.edu" },
  { name: "Northern Virginia Community College", domain: "nvcc.edu" },
  { name: "Bunker Hill Community College", domain: "bhcc.edu" },
  { name: "Portland Community College", domain: "pcc.edu" },
  { name: "Salt Lake Community College", domain: "slcc.edu" },
  { name: "Columbus State Community College", domain: "cscc.edu" },
];

/** Fast lookup: university name → clearbit domain */
const domainMap = new Map<string, string>(
  US_UNIVERSITIES.map((u) => [u.name.toLowerCase(), u.domain])
);

/**
 * Try to find a Clearbit-fetchable domain for the given school name.
 * Returns empty string if unknown (so the logo component shows nothing).
 */
export function getSchoolDomain(name: string): string {
  const key = name.trim().toLowerCase();
  if (domainMap.has(key)) return domainMap.get(key)!;

  // Partial fuzzy match on first word
  for (const [n, d] of domainMap) {
    if (n.includes(key) || key.includes(n)) return d;
  }
  return "";
}

/** All university names as a flat string array for autocomplete */
export const UNIVERSITY_NAMES: string[] = US_UNIVERSITIES.map((u) => u.name);
